[package]
name = "fluvio-java"
version = "0.0.2"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
resolver = "2"

[lib]
crate-type = ["cdylib"]
name = "fluvio_java"

[build-dependencies]
flapigen = "0.6.0-pre7"
env_logger = "^0.9"
bindgen = { version = "0.59.0", default-features = false, features = ["logging", "runtime", "which-rustfmt"] }

[dependencies]
log = "^0.4.6"
fluvio = "0.8.4"
fluvio-future = { version = "0.3.5", features = ["task", "io"] }
