[package]
name = "fluvio-java"
version = "0.0.2"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]

[lib]
crate-type = ["cdylib"]
name = "fluvio_java"

[build-dependencies]
flapigen = "0.6.0-pre7"
env_logger = "^0.7"
bindgen = { version = "0.57.0", default-features = false, features = ["logging", "runtime", "which-rustfmt"] }

[dependencies]
log = "^0.4.6"
fluvio = { version = "0.6" }
fluvio-future = { version = "0.1.15", features = ["task", "io"] }
