[package]
name = "fluvio-java"
version = "0.10.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
resolver = "2"

[lib]
crate-type = ["cdylib"]
name = "fluvio_java"

[build-dependencies]
flapigen = "0.6.0-pre7"
env_logger = "^0.10"
bindgen = { version = "0.64.0", default-features = false, features = ["logging", "runtime", "which-rustfmt"] }

[dependencies]
log = "^0.4.17"
fluvio = { features = ["admin"], git = "https://github.com/infinyon/fluvio.git", rev = "0483f594a7e9e25accd40c8ed56f4064f71476be" }
fluvio-future = { version = "0.5.1", features = ["task", "io"] }
anyhow = "1.0.70"