/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fluvio.client.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
    }
}
