name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ staging, trying ]
  pull_request:
    branches: [ main ]

jobs:
  smoke_test:
    name: Smoke test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        # Add Java 16 when https://github.com/gradle/gradle/issues/13481 has a
        # better work around.
        java: [8, 11, 16, 17]
        exclude:
          - os: macos-latest
            java: 8

    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'

      - name: Build
        run: |
          make assemble

      - name: Run Test
        run: |
          make test

      - name: Run Checkstyle
        run: |
          make checkstyle          

      - name: Upload Test Results
        timeout-minutes: 1
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-results
          path: /home/runner/work/fluvio-client-java/fluvio-client-java/lib/build/reports/tests/test/

  done:
    name: Done
    needs:
      - smoke_test
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"
