name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  smoke_test:
    name: Smoke test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        # Add Java 16 when https://github.com/gradle/gradle/issues/13481 has a
        # better work around.
        java: [8, 11, 15, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Setup java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          make assemble

      - name: Run Test
        run: |
          make test

      - name: Upload Test Results
        timeout-minutes: 1
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: gradle-test-results
          path: /home/runner/work/fluvio-client-java/fluvio-client-java/lib/build/reports/tests/test/
