name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:

  build_rust_libs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust: [stable]
        java: [8, 11, 16, 17]
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Setup java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'

      - name: Build Rust
        run: ./gradlew rust-deploy

      - name: "Upload Rust Static lib for ${{matrix.os}} for java - ${{matrix.java}}"
        uses: actions/upload-artifact@v2
        with:
          name: "${{matrix.os}}-${{matrix.java}}"
          path: ./fluvio/libs/
          retention-days: 5

      - name: 'Upload Java src - linux'
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: "java-src-${{matrix.java}}"
          path: ./fluvio/src/main/java/com/infinyon/fluvio/
          retention-days: 5

  publish:
    runs-on: [ubuntu-latest]
    needs: [build_rust_libs]
    strategy:
      matrix:
        rust: [stable]
        java: [8, 11, 16, 17]
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Setup java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'

      - name: Download MacOS Lib
        uses: actions/download-artifact@v2
        with:
          name: "macos-latest-${{matrix.java}}"
          path: ./fluvio/libs/

      - name: Download Linux Lib
        uses: actions/download-artifact@v2
        with:
          name: "ubuntu-latest-${{matrix.java}}"
          path: ./fluvio/libs/

      - name: Download Java src
        uses: actions/download-artifact@v2
        with:
          name: "java-src-${{matrix.java}}"
          path: ./fluvio/src/main/java/com/infinyon/fluvio/

      - name: Publish local
        run: |
          make publish-local
          ls ./fluvio/libs/ ./fluvio/build/resources/main/
          jar tf ~/.m2/repository/com/infinyon/fluvio-*/*/fluvio-*-*.jar

      - name: Publish package
        run: |
          make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
