name: Push snapshot to Maven repo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_macos_rust_libs:
    name: Build native library for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Deploy package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: rust-deploy
      - name: "Upload Rust Static lib"
        uses: actions/upload-artifact@v3
        with:
          name: "macos-latest-libs"
          path: ./fluvio/libs/
          retention-days: 5

  do-snapshot-publish:
    name: Push snapshot to Sonatype OSS
    needs: [build_macos_rust_libs]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'infinyon'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java and credentials
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Download MacOS Lib
        uses: actions/download-artifact@v3
        with:
          name: "macos-latest-libs"
          path: ./fluvio/libs/
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
