name: Push snapshot to Maven repo

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  do-snapshot-publish:
    name: Push snapshot to Sonatype OSS
    runs-on: ubuntu-latest
    if: github.repository_owner == 'infinyon'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java and credentials
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@e88ed3e650b26bd116cfee53cf198c1f6856682d
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}